### ISSUE TITLE
Fix Mouse Input Delay

### ISSUE THREAD

**Issue by Richard-L** [freeserf/freeserf#128] opened 2013-07-04 22:07 UTC
Mouse movement has significant input delay. Almost feels like Amiga which is kinda nostalgic in its own way, but please, do fix lag.

**Comment by genodeftest** [comment] 2016-03-06 22:34
Isn't this a duplicate of #50 which has been fixed long time ago?

**Comment by wdigger** [comment] 2016-05-05 13:52
This issue is still affected.

**Closed** 2016-05-05 17:13 UTC
Labels: need-info, windows
