### ISSUE TITLE
graphics broken after loading "save"

### ISSUE THREAD

**Issue by zdechlak** [freeserf/freeserf#135] opened 2013-07-05 01:14 UTC
error after loading game - graphics broken
1. load "save game"
2. changed castle
3. graphic broken ;p
- video: http://www.youtube.com/watch?v=Ng_78Xd6_y8&feature=youtu.be

Daily bulid :)

**Comment by wdigger** [comment] 2016-07-27 14:23
I think crash is due to player switching instead of loading games.

**Comment by wdigger** [comment] 2019-01-20 09:19
Can't reproduce in 0.3, fixed indirectly.

**Closed by wdigger** 2019-01-20 09:19 UTC
Labels: bug
