### ISSUE TITLE
Resource stats are bugged

### ISSUE THREAD

**Issue by Pyrdacor** [freeserf/freeserf#469] opened 2020-07-23 13:56 UTC
`Player::update_stats` uses the player `index` instead of the resource count index. You have to add a parameter called `index` and pass the resource count index to the function. Otherwise the resource statistics won't work.

Had the same issue with [freeserf.net](https://github.com/Pyrdacor/freeserf.net/issues/114) and now it works as expected there.

**Comment by tlongstretch** [comment] 2022-01-18 23:16
I fixed in Forkserf, thanks!

**Comment by wdigger** [comment] 2023-01-06 22:20
@tlongstretch can you make a PR for this one?

**Comment by tlongstretch** [comment] 2023-01-07 00:52
There's a bit more than just that... Player::update_stats needs to shift the array before setting the value.  Also, the popup isn't checking interface->get... stats function variable it is using a local one so it never changes from the default resource, and its off-by one so it selects the resource one-off from the clicked resource.

details here:
https://github.com/forkserf/forkserf/commit/054586f0f0180d081efd21b136cd6409ca1f3e82

(ignore the ai_pathfinder stuff, I forgot to commit that separately)

**Comment by tlongstretch** [comment] 2023-01-07 00:55
yeah I can do a pull request, but there are way more important issues that should be fixed also :)  crash bugs

**Comment by tlongstretch** [comment] 2023-01-07 01:28
It has been so long since this I looked at this, but by coincidence I had ended up revisiting this today.  It wasn't clear from looking at the code if the history was intended to have a rolling offset, or to be shifted each update so that one end represents the newest record and other end the oldest.  I tried array shifting so that the newest record is always the lowest index and other records are incremented by one, and it worked perfectly.

I can't actually remember how Pyrdacor's fix works.  I think I saw a complaint that the graph was drawn "wrong" as in not oldest-left to newest-right?

**Closed** 2023-01-08 10:10 UTC
